### ISSUE TITLE
Plugin compatability with QGSIS 3.8

### ISSUE THREAD

**Issue by shakythesherpa** [KTH-dESA/Cluster-based_extraction_OnSSET#1]
Do you know if these plugins are compatible with QGIS 3.8 . I am running into issues installing it via zip file.

**Comment by babakkhavari** [comment]
Hi, We have not tested the plugins on QGIS 3.8. It is important that the plugin is installed in the right version as different version are not compatible.
 
Are you running in to problems with all versions?
